# This is an example configuration file for the integration service.
# Please copy this file to config.yaml file in the integration folder and edit it to your needs.
initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}" # Can be loaded via environment variable: PORT_CLIENT_ID
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}" # Can be loaded via environment variable: PORT_CLIENT_SECRET
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  identifier: sonarqube-integration
  # The type of the integration.
  type: "sonarqube"
  config:
    sonarApiToken: "{{ from env SONAR_API_TOKEN }}"
    sonarUrl: "{{ from env SONAR_URL }}"
    sonarOrganizationID: "{{ from env SONAR_ORGANIZATION_ID }}"
    appHost: "{{ from env APP_HOST }}"