deleteDependentEntities: true
createMissingRelatedEntities: true
enableMergeEntity: true
resources:
  - kind: /api/v1/users
    selector:
      query: 'true'
      method: GET
      data_path: .data
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"user"'
          properties:
            email: .email
            department: .department
            is_active: .is_active
            created_at: .created_at
            last_login: .last_login
            role: .role


