site_name: Ocean Documentation
site_url: https://app.getport.io
theme:
  name: material
  logo: ./assets/OceanSymbol.svg
  favicon: ./assets/OceanSymbol.svg
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


repo_name: port-labs/Port-Ocean
repo_url: https://github.com/port-labs/Port-Ocean

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          paths: [../port_ocean]
          options:
            show_root_heading: true
            heading_level: 2
            show_category_heading: true
            show_source: false
            show_bases: false



nav:
  - ğŸ  Home: index.md
  - ğŸ‰ Getting Started:
    - ğŸ› ï¸ Installation: ./getting-started/installation.md
    - âš¡ï¸ Quickstart: ./getting-started/quickstart.md
    - ğŸš€ Deployment: ./getting-started/deployment.md
    - ğŸ“¦ Publishing: ./getting-started/publishing.md
  - ğŸ’» Cli: ./cli.md
  - ğŸ“š Guides: ./guides/index.md
  - ğŸ”§ Development: ./development/index.md
  - ğŸ¤ Contributing:
      - ğŸ’¡ Suggesting a Feature: ./contributing/suggesting-feature.md
      - ğŸ Reporting a Bug: ./contributing/reporting-bug.md
      - ğŸ“ Suggesting a Docs change: ./contributing/suggesting-docs-change.md
      - â‰ï¸ Asking a Question: ./contributing/asking-question.md
  - ğŸ” References:
      - core:
          - integrations: ./references/core/integrations.md
          - handlers: ./references/core/handlers.md
          - event listener: ./references/core/event-listener.md
          - models: ./references/core/models.md
          - types: ./references/core/types.md
      - clients: ./references/clients.md
      - config: ./references/config.md
      - consumers: ./references/consumers.md
      - context: ./references/context.md
      - middleware: ./references/middleware.md
      - ocean: ./references/ocean.md
      - run: ./references/run.md
      - utils: ./references/utils.md
  - ğŸ“œ License: ./license.md
  - ğŸ“… Release Notes: ../../CHANGELOG.md
  - ğŸ¤” FAQ: ./faq.md
